"""Changing the length of the password field for users.

Revision ID: 11283e5b91d7
Revises: 4b0639d842d5
Create Date: 2011-12-15 22:19:45.811857

"""

# downgrade revision identifier, used by Alembic.
down_revision = '4b0639d842d5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password', type_=sa.String(80))
    ### end Alembic commands ###

def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password', type_=sa.String(120))
    ### end Alembic commands ###
