"""Adding a revision field to the guides.

Revision ID: 41806cbf9cf0
Revises: 11283e5b91d7
Create Date: 2011-12-27 23:38:08.784833

"""

# downgrade revision identifier, used by Alembic.
down_revision = '11283e5b91d7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guides', sa.Column('description', sa.String(length=20000), nullable=True))
    ### end Alembic commands ###

def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guides', 'description')
    ### end Alembic commands ###
